let respuesta = prompt("Introduce tu nombre")
const fecha = new Date()
const año = fecha.getFullYear()
const mes = fecha.getMonth()
const dia = fecha.getMinutes()
console.log(`${fecha}/${mes}/${año}`)
